'use strict';

export class PreTexts {
    static texts = {
        copyright: {
            ko: '© Smilegate. All Rights Reserved.',
            en: '© Smilegate. All Rights Reserved.',
            zht: '© Smilegate. All Rights Reserved.',
            zhs: '© Smilegate. All Rights Reserved.',
            ja: '© Smilegate. All Rights Reserved.',
        },
        retry: {
            ko: '화면을 터치하세요',
            en: 'Tap to retry',
            zht: '點擊屏幕',
            zhs: '点击屏幕',
            ja: 'タップして再試行する',
        },
		time_am: {
			ko: '오전',
			en: 'AM',
			zht: '上午',
			zhs: '上午',
			ja: 'AM',
		},
		time_pm: {
			ko: '오후',
			en: 'PM',
			zht: '下午',
			zhs: '下午',
			ja: 'PM',
		},
		time_utc: {
			ko: 'UTC',
			en: 'UTC',
			zht: '協調世界時',
			zhs: '协调世界时',
			ja: 'UTC',
		},
		maintenance_time_remain: {
			ko: '남은 시간',
			en: 'Remaining time',
			zht: '剩餘時間',
			zhs: '剩余时间',
			ja: '残り時間',
		},
		connect_error: {
			ko: '게임 접속 장애가 발생하였습니다. 다시 접속해주시기 바랍니다.',
			en: 'Game connection error occurred. Please reconnect.',
			zht: '遊戲連接失敗，請重新連接。',
			zhs: '游戏连接失败，请重新连接。',
			ja: 'ゲーム接続エラーが発生しました。再接続してください。',
		},
		maintenance: {
			ko: "점검중",
			en: "Maintenance",
			zht: "維護中",
			zhs: "维护中",
			ja: "メンテナンス中",
		},
		maintenance_description: {
			ko: "나이트메어 호에 승선까지 조금만 기다려 주세요",
			en: "The SS Nightmare will be ready for boarding shortly. Thank you for waiting.",
			zht: "請稍等片刻，即將登上「夢境號」",
			zhs: "请稍等片刻，即将登上「梦境号」",
			ja: "ナイトメア号への乗艦まで、しばらくお待ちください。",
		},
		maintenance_finished: {
			ko: "점검이 완료되었습니다<br>화면을 터치해주세요.",
			en: "Maintenance finished.<br>Tap to continue.",
			zht: "維護已完成。<br>點擊屏幕繼續。",
			zhs: "维护已完成。<br>点击屏幕继续。",
			ja: "メンテナンスが完了しました。<br>タップして続行してください。",
		},
		build_number: {
			ko: "build number",
			en: "build number",
			zht: "版本",
			zhs: "版本",
			ja: "build number",
		},
		patch_version: {
			ko: "patch version",
			en: "patch version",
			zht: "補丁",
			zhs: "补丁",
			ja: "patch version",
		},
		notice: {
			ko: "공지사항",
			en: "Notice",
			zht: "公告",
			zhs: "公告",
			ja: "お知らせ",
		},
		app_upgrade_message: {
			ko: "최신 앱 버전으로 업데이트 해주세요.",
			en: "Please update to the latest app version.",
			zht: "請將應用程序更新至最新版本。",
			zhs: "请将应用程序更新至最新版本。",
			ja: "最新のアプリケーションバージョンに更新してください。",
		},
		pre_patch_complete: {
			ko: "사전 다운로드가 완료되었습니다.<br>화면을 터치해주세요.",
			en: "Pre-download completed.<br>Tap to continue.",
			zht: "預先下載已完成。<br>點擊屏幕繼續。",
			zhs: "预先下载已完成。<br>点击屏幕继续。",
			ja: "事前ダウンロードが完了しました。<br>タップして続行してください。",
		},
		select_server: {
			ko: "서버 선택",
			en: "Select Server",
			zht: "選擇伺服器",
			zhs: "选择伺服器",
			ja: "サーバー選択",
		},
		select_voice: {
			ko: "음성 선택",
			en: "Select Voice",
			zht: "選擇語音",
			zhs: "选择语音",
			ja: "音声を選択",
		},
		select_language: {
			ko: "언어 선택",
			en: "Select Language",
			zht: "選擇語言",
			zhs: "选择语言",
			ja: "言語を選択",
		},		
		btn_cancel: {
			ko: "취소",
			en: "Cancel",
			zht: "取消",
			zhs: "取消",
			ja: "キャンセル",
		},
		btn_confirm: {
			ko: "확인",
			en: "Confirm",
			zht: "確認",
			zhs: "确认",
			ja: "確認",
		},
		download_cdn_title: {
			ko: "콘텐츠 다운로드",
			en: "Content Download",
			zht: "下載內容",
			zhs: "下载内容",
			ja: "コンテンツダウンロード",
		},
		download_cdn_pre_title: {
			ko: "사전 다운로드",
			en: "Pre-download",
			zht: "預先下載",
			zhs: "预先下载",
			ja: "事前ダウンロード",
		},
		download_cdn_main: {
			ko: "새로운 게임 리소스를 다운로드 할 수 있습니다.<br>지금 다운로드 하시겠습니까?",
			en: "You can download new game resources.<br>Would you like to download now?",
			zht: "可下載新的遊戲資源。<br>確定要現在下載嗎？",
			zhs: "可下载新的游戏资源。<br>确定要现在下载吗？",
			ja: "新しいゲーム リソースをダウンロードできます。<br>今ダウンロードしますか？",
		},
		download_cdn_sub: {
			ko: "LTE / 5G 환경에서는 추가 데이터 요금이 발생할 수 있습니다.<br>WIFI 환경에서 다운로드하는 것을 권장드립니다.",
			en: "In LTE / 5G environments, additional data charges may occur.<br>Downloading in a WIFI environment is recommeded.",
			zht: "在LTE/5G環境下可能會産生額外的流量費。<br>建議在WIFI環境中下載。",
			zhs: "在LTE/5G环境下可能会产生额外的流量费。<br>建议在WIFI环境中下载。",
			ja: "LTE/5G環境では追加データ料金が発生することがあります。<br>WIFI環境でダウンロードすることをお勧めします。",
		},
		metadata_downloading: {
			ko: "새로운 리소스 목록 수신 중",
			en: "Fetching new resource list",
			zht: "正在獲取新資源列表",
			zhs: "正在获取新资源列表",
			ja: "新規リソースリスト読み込み中",			
		},
		content_downloading: {
			ko: "리소스 다운로드 중",
			en: "Downloading Resources",
			zht: "正在下載遊戲資源",
			zhs: "正在下载游戏资源",
			ja: "リソースダウンロード中",
		},
		content_extracting: {
			ko: "리소스 압축 해제 중",
			en: "Extracting Resources",
			zht: "正在解壓遊戲資源",
			zhs: "正在解压游戏资源",
			ja: "リソース解凍中",
		},
		language_english: {
			ko: "영어",
			en: "English",
			zht: "英語",
			zhs: "英语",
			ja: "英語",
		},
		language_korean: {
			ko: "한국어",
			en: "Korean",
			zht: "韓語",
			zhs: "韩语",
			ja: "韓国語",
		},
		language_japanese: {
			ko: "일본어",
			en: "Japanese",
			zht: "日語",
			zhs: "日语",
			ja: "日本語",
		},
		language_chinese: {
			ko: "중국어",
			en: "Chinese",
			zht: "漢語",
			zhs: "汉语",
			ja: "中国語",
		},
		language_change_sub: {
			ko: "게임 내 환경설정에서도 변경할 수 있습니다.",
			en: "You can also change the voice in the Settings.",
			zht: "可在遊戲設定變更。",
			zhs: "可在游戏设定变更。",
			ja: "ゲーム設定でも変更できます。",
		},
		patch_error: {
			ko: "네트워크 연결 상태가 원활하지 않습니다.네트워크 재연결 시 다운로드는 이어서 진행됩니다.",
			en: "Patch error occurred.",
			zht: "補丁錯誤發生。",
			zhs: "补丁错误发生。",
			ja: "パッチエラーが発生しました。",
		},
		disk_space_error: {
			ko: "저장 공간이 부족합니다. 저장 공간을 확보한 후 다시 시도해주세요.",
			en: "Insufficient storage space. Please free up some space and try again.",
			zht: "儲存空間不足。請釋放一些空間後再試一次。",
			zhs: "存储空间不足。请释放一些空间后再试一次。",
			ja: "ストレージ容量が不足しています。容量を確保してから再度お試しください。",
		},
		kb:{
			ko: "KB",
			en: "KB",
			zht: "KB",
			zhs: "千字节",
			ja: "KB",
		},
		gb:{
			ko: "GB",
			en: "GB",
			zht: "GB",
			zhs: "千兆字节",
			ja: "GB",
		},
		maintenance_time_start: {
			ko: "시작 시간",
			en: "Start Time",
			zht: "開始時間",
			zhs: "开始时间",
			ja: "開始時間",
		},
		maintenance_time_end: {
			ko: "종료 시간",
			en: "End Time",
			zht: "結束時間",
			zhs: "结束时间",
			ja: "終了時間",
		},
		maintenance_patch_note: {
			ko: "패치 노트",
			en: "Patch Note",
			zht: "補丁說明",
			zhs: "补丁说明",
			ja: "パッチノート",
		},
		maintenance_patch_notice: {
			ko: "공지사항",
			en: "Notice",
			zht: "公告",
			zhs: "公告",
			ja: "お知らせ",
		},
		maintenance_patch_sns: {
			ko: "SNS",
			en: "SNS",
			zht: "SNS",
			zhs: "SNS",
			ja: "SNS",
		},
		maintenance_status_longer: {
			ko: "연장점검",
			en: "Extended",
			zht: "延長維護",
			zhs: "延长维护",
			ja: "延長メンテナンス",
		},
		maintenance_status_shorter: {
			ko: "조기종료",
			en: "Early End",
			zht: "提前結束",
			zhs: "提前结束",
			ja: "早期終了",
		},
		ui_game_login: {
			ko: "로그인",
			en: "Login",
			zht: "登入",
			zhs: "登录",
			ja: "ログイン",
		},
		publisher_initialize_failed: {
			ko: "SDK 초기화 실패",
			en: "SDK initialization failed",
			zht: "SDK 初始化失敗",
			zhs: "SDK 初始化失败",
			ja: "SDK 初期化失敗",
		},
		touch_to_start: {
			ko: "T O U C H   T O   S T A R T",
			en: "T O U C H   T O   S T A R T",
			zht: "T O U C H   T O   S T A R T",
			zhs: "点击开始",
			ja: "T O U C H   T O   S T A R T",
		},
		limited_play_test: {
			ko: "사전 플레이 테스트",
			en: "Limited play test",
			zht: "事前遊玩測試",
			zhs: "事前遊玩測試",
			ja: "特別先行テスト",
		},
		permission_popup_required: {
			ko: "필수",
			en: "Required",
			zht: "必須",
			zhs: "必須",
			ja: "必須",
		},
		permission_popup_optional: {
			ko: "선택",
			en: "Optional",
			zht: "選擇",
			zhs: "选择",
			ja: "選択",
		},
		permission_popup_tip: {
			ko: "※ 선택적 접근 권한에 동의하지 않으셔도 게임 이용이 가능합니다.",
			en: "※ You can play the game without agreeing to the optional Permission requests.",
			zht: "※ 即使不同意選擇性訪問權限，也可以使用遊戲。",
			zhs: "※ 即使不同意选择性访问权限，也可以使用游戏。",
			ja: "※ 選択的アクセス権限に同意しなくてもゲームのご利用は可能です。",
		},
		permission_popup_title: {
			ko: "권한 설정",
			en: "Permissions",
			zht: "權限設置",
			zhs: "权限设置",
			ja: "権限設定",
		},
		permission_camera_title: {
			ko: "카메라",
			en: "Camera",
			zht: "相機",
			zhs: "相机",
			ja: "カメラ",
		},
		permission_camera_description: {
			ko: "사진 등 촬영을 위해 사용됩니다.",
			en: "Used for taking photographs, etc",
			zht: "用於拍攝照片等",
			zhs: "用于拍摄照片等",
			ja: "写真等の撮影に使用",
		},
		permission_microphone_title: {
			ko: "마이크",
			en: "Microphone",
			zht: "麥克風",
			zhs: "麦克风",
			ja: "マイク",
		},
		permission_microphone_description: {
			ko: "동영상 녹화 시 음성 녹음을 하기 위해 사용됩니다.",
			en: "Used for voice recording when recording a video",
			zht: "用於錄視頻時錄音",
			zhs: "用于录视频时录音",
			ja: "動画録画時の音声録音に使用",
		},
		permission_tracking_title: {
			ko: "추적",
			en: "Tracking",
			zht: "追蹤",
			zhs: "追踪",
			ja: "追跡",
		},
		permission_tracking_description: {
			ko: "관심사에 맞는 콘텐츠와 이벤트를 제공하는데 사용됩니다.",
			en: "Used for providing content and events that fit your interests",
			zht: "用於提供符合興趣的內容和活動",
			zhs: "用于提供符合兴趣的内容和活动",
			ja: "関心事に合ったコンテンツやイベント提供時に使用",
		},
		permission_push_title: {
			ko: "알림",
			en: "Notification",
			zht: "通知",
			zhs: "通知",
			ja: "通知",
		},
		permission_push_description: {
			ko: "앱 푸시 알림을 위해 사용됩니다.",
			en: "Used for App push notifications",
			zht: "用於應用程序推送通知",
			zhs: "用于应用程序推送通知",
			ja: "アプリプッシュ通知に使用",
		},
		permission_photo_title: {
			ko: "사진",
			en: "Photos",
			zht: "照片",
			zhs: "照片",
			ja: "写真",
		},
		permission_photo_description: {
			ko: "기기에 저장된 사진 업로드를 위해 사용됩니다.",
			en: "Used to upload photographs stored on your device",
			zht: "用於上傳存儲在設備中的照片",
			zhs: "用于上传存储在设备中的照片",
			ja: "デバイスに保存された写真のアップロードに使用",
		},
		permission_photo_addition: {
			ko: "설정 > 개인 정보 보호 > 사진 > 일회용 사진 선택 권한이 있는 앱",
			en: "Settings > Privacy > Photos > Apps with Limited Access to Photo",
			zht: "設置 > 個人信息保護 > 照片 > 受限制的取用權限的應用程序",
			zhs: "设置 > 个人信息保护 > 照片 > 受限制的取用权限的应用程序",
			ja: "設定 > 個人情報保護 > 写真 > 制限付きアクセスを持つアプリ",
		},
		//중국 전용 apple login 문구
		apple_login_title: {
			ko: "Apple로 로그인",
			en: "Sign in with Apple",
			zht: "使用Apple登入",
			zhs: "通过Apple登陆",
			ja: "Appleでサインイン",
		},
		patch_version_checking: {
			ko: "패치 버전 확인 중",
			en: "Verifying patch version",
			zht: "正在驗證修補版本",
			zhs: "正在验证补丁版本",
			ja: "パッチバージョン確認中",
		},		
		ui_patch_loading_title: {
			ko: "패치 버전 확인 중",
			en: "Verifying patch version",
			zht: "正在驗證修補版本",
			zhs: "正在验证补丁版本",
			ja: "パッチバージョン確認中",
		},
    };

    static getText(id) {
        const text = this.texts[id];
        const userLang = this.getUserLanguage();
		const text_found = text ? text[userLang] : `${id}_${userLang}`;
        return text_found.replace('<br>', '\n');
    }

    static getUserLanguage() {
		let lang = _getenv('user.lang', 'en');
		if (lang == "zh") {
			lang = "zhs";
		}
        return lang;
    }
}

exports.PreTexts = PreTexts;
